#!/usr/bin/env bash

[ -r $CLUSTER_PATH/console ] || mkfifo $CLUSTER_PATH/console

# We must have at least one writer
sleep infinity > "$CLUSTER_PATH/console" &

cd "$DST_HOME/bin"

exec ./dontstarve_dedicated_server_nullrenderer \
    -persistent_storage_root "$(dirname "$CLUSTER_PATH")" \
    -conf_dir "." \
    -cluster "$(basename "$CLUSTER_PATH")" \
    -shard "$SHARD_NAME" \
    "$@" < <({ stdbuf -oL cat "$CLUSTER_PATH/console" & stdbuf -oL cat & })
