#!/usr/bin/env bash

# We must have at least one writer
sleep infinity > "$DSTA_HOME/console" &

cd "$DST_HOME/bin"

exec ./dontstarve_dedicated_server_nullrenderer \
    -persistent_storage_root "$(dirname "$CLUSTER_PATH")" \
    -conf_dir "." \
    -cluster "$(basename "$CLUSTER_PATH")" \
    -shard "$SHARD_NAME" \
    -backup_log_count "$BACKUP_LOG_COUNT" \
    "$@" < <({ stdbuf -oL cat "$DSTA_HOME/console" & stdbuf -oL cat & })
